### ISSUE TITLE
Update avatar

### ISSUE THREAD

**Issue by vipera7** [Schmidt-DevOps/Seafile-PHP-SDK#17]
### Expected behaviour
I would like to update the avatar to a particular user
### Actual behaviour
Missing fonction
#### Which call are you making?
Adding a fonction
#### Do you have permissions to create a new directory?
Yes
#### Do you have permissions to read the directory?
Yes
#### Does the Seafile server work OK otherwise?
Yes
#### Did you obtain an API token from the server and has it been stored correctly?
Yes
#### Which branch or tag of the Seafile-PHP-SDK are you using?
v.1.0.1
#### Which PHP version are you using?
PHP 5.6.32
#### What is the version of the Seafile server you are using?
6.1.2
#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64bits
#### Are there error messages in the Seafile server's log files? If so, please post them.
No

Thank you :)

**Comment by rene-s** [comment]
Hello, the goal of this SDK is to enable PHP apps to utilize the Seafile Web API: 

https://manual.seafile.com/develop/web_api.html

Seafile's Web API does not seem to offer the option to update the avatar, thus updating the avatar is not the scope of this SDK.

I would suggest you kindly ask the Seafile developers for an API endpoint that enables you to update the avatar image, then that would also be the scope of this SDK.

Regards
Rene

**Comment by vipera7** [comment]
We can update the avatar here : https://manual.seafile.com/develop/web_api_v2.1.html#update-user-avatar

**Comment by rene-s** [comment]
Well, I was wrong then :)

Ok I will have a look into it. I cannot give an estimate on when this endpoint will be covered by the SDK though as I am currently pretty swamped.

Regards
Rene

**Comment by rene-s** [comment]
Hello, I still intend to implement this at a later time. This is a V2.1 API endpoint though and the SDK only implements V2 API endpoints so implementing this feature is not as easy as I thought it would be because I have to prepare the whole SDK for API V2.1 which I have not done yet.

Regards
Rene
