### ISSUE TITLE
Upload directory

### ISSUE THREAD

**Issue by vipera7** [Schmidt-DevOps/Seafile-PHP-SDK#18]
### Expected behaviour
I would like to upload a whole directory instead files.
### Actual behaviour
Cannot upload directory
#### Which call are you making?
Adding a fonction
#### Do you have permissions to create a new directory?
Yes
#### Do you have permissions to read the directory?
Yes
#### Does the Seafile server work OK otherwise?
Yes
#### Did you obtain an API token from the server and has it been stored correctly?
Yes
#### Which branch or tag of the Seafile-PHP-SDK are you using?
v.1.0.1
#### Which PHP version are you using?
PHP 5.6.32
#### What is the version of the Seafile server you are using?
6.1.2
#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64bits
#### Are there error messages in the Seafile server's log files? If so, please post them.
No

Thank you!

**Comment by rene-s** [comment]
Hello vipera7,

does the API provide an endpoint for uploading a whole directory? Does not seem to be the case.

The SDK will only implement methods for official API endpoints (and only V2 at the moment, not V2.1).

Regards
Rene
