### ISSUE TITLE
How to get notification

### ISSUE THREAD

**Issue by vipera7** [Schmidt-DevOps/Seafile-PHP-SDK#19]
### Expected behaviour
Retrieve all notifications from user.
### Actual behaviour
Function doesn't exist

#### Which call are you making?
Create a new function
#### Do you have permissions to create a new directory?
Yes
#### Do you have permissions to read the directory?
Yes
#### Does the Seafile server work OK otherwise?
Yes
#### Did you obtain an API token from the server and has it been stored correctly?
Yes
#### Which branch or tag of the Seafile-PHP-SDK are you using?
v.1.0.1
#### Which PHP version are you using?
PHP 5.6.32
#### What is the version of the Seafile server you are using?
6.1.2
#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64bits
#### Are there error messages in the Seafile server's log files? If so, please post them.
Nop

**Comment by rene-s** [comment]
Hello vipera7,

I am sorry I do not know how to access user notifications. Are the notifications supposed to be accessible via API? I cannot find anything on that in the docs.

Regards
Rene
