### ISSUE TITLE
Named file uploaded

### ISSUE THREAD

**Issue by FlorientR** [Schmidt-DevOps/Seafile-PHP-SDK#22]
### Expected behaviour
Upload a file with a specific name

### Actual behaviour
The name is the php tmp filename

### Steps to reproduce the behaviour
$file = new File($this->client);
$file->upload($this->library, $fileUri, dirname($path), basename($path));

#### Which call are you making?
Upload File

#### Do you have permissions to create a new directory?
Yes

#### Do you have permissions to read the directory?
Yes

#### Does the Seafile server work OK otherwise?
Yes

#### Did you obtain an API token from the server and has it been stored correctly?
Yes

#### Which branch or tag of the Seafile-PHP-SDK are you using?
Latest

#### Which PHP version are you using?
7.2

#### What is the version of the Seafile server you are using?
6.x

#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64 bits

#### Are there error messages in the Seafile server's log files? If so, please post them.
No

Hi, when I want to upload a new file, I give a filename for the api but the name on seafile server is the php tmp filename. 

On Resource\File.php, on getMultiPartParams function, the multipart of file must contains 
`'filename' => $fileBaseName`
for correct named file on Seafile.

Buy,
Flo

**Comment by rene-s** [comment]
Hi Flo, I am assuming that you are using v1.0.1. Please try the example from `bin/examples/file_history.php` . I have just checked it, it should work with Seafile server 7.1.3. 

v1.0.1 should work with Seafile server 6.x but since I have updated all my servers to 7.x I cannot verify this anymore. I suggest you also try it with 7.x if you have the opportunity.

Regards
Rene

**Comment by FlorientR** [comment]
Hi,

The Seafile server is the server of my company so I haven't access to the
server. I will talk about to my sysadmin but for the moment, I'm not able
to upgrade to 7.x.

Thanks for your reply,
Flo.

Le sam. 16 mai 2020 à 17:39, Rene Schmidt <notifications@github.com> a
écrit :

**Comment by rene-s** [comment]
Hello Flo, thank you very much for letting me know. I can confirm `$newFilename` parameter of `File::upload()` is not working as intended. I have noted it in the readme. 

Please feel free to submit a pull request with a fix and updated tests.

Regards
Rene
