### ISSUE TITLE
Upload File Error

### ISSUE THREAD

**Issue by adnhacker** [Schmidt-DevOps/Seafile-PHP-SDK#24]
Hi, i recently update from 7.0 to 7.1.4. But when i trying to update a file into directory, i get 403 error. Only if i try in / works fine

### Steps to reproduce the behaviour
$fileResource = new File($this->cliente);
        $fileToUpload = $file;
        $dir = $path; // it's /path/to/directory/to/upload/
        return $fileResource->upload($lib, $fileToUpload, $dir);
#### Do you have permissions to create a new directory?
Yes

#### Do you have permissions to read the directory?
Yes

#### Does the Seafile server work OK otherwise?
Yes

#### Did you obtain an API token from the server and has it been stored correctly?
Yes

#### Which PHP version are you using?
7.4

#### What is the version of the Seafile server you are using?
7.1.4

#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64Bits

**Comment by rene-s** [comment]
Thanks for letting me know. Check out the develop branch for a fixed version
