### ISSUE TITLE
Missing seperator in File::rename

### ISSUE THREAD

**Issue by moltox** [Schmidt-DevOps/Seafile-PHP-SDK#31]
### Expected behaviour
Rename item
### Actual behaviour
"Path is missing or invalid" error_msg
### Steps to reproduce the behaviour
Get a (file) directoryItem (which lives in a directory) for rename
$fileResource = new File($client);

$fileResoruce->rename($lib, $directoryItem, 'foo.bar');

### Other helpful information
In Resource/File row 334 ( $filePath = $dirItem->dir . $dirItem->name; ) should be $filePath = $dirItem->dir . '/' . $dirItem->name;

**Comment by rene-s** [comment]
Great, thanks! Feel free to create a pull request.
