### ISSUE TITLE
latest version of guzzlehttp use sink instead of save_to in Resource/File.php

### ISSUE THREAD

**Issue by StephanTie** [Schmidt-DevOps/Seafile-PHP-SDK#34]
please change use sink command instead of save_to in function downloadFromDir() in  File.php .

  public function downloadFromDir(
      LibraryType $library,
      DirectoryItem $item,
      string $localFilePath,
      string $dir,
      int $reuse = 1
  ): ResponseInterface
  {
      if (is_readable($localFilePath)) {
          throw new Exception('File already exists');
      }
  
      $downloadUrl = $this->getDownloadUrl($library, $item, $dir, $reuse);
  
  //        return $this->client->request('GET', $downloadUrl, ['save_to' => $localFilePath]);  // replace by next line
      return $this->client->request('GET', $downloadUrl, ['sink' => $localFilePath]);
  }

**Comment by StephanTie** [comment]
also apllies to 
    public function downloadRevision(
        LibraryType $library,
        DirectoryItem $dirItem,
        FileHistoryItem $fileHistoryItem,
        string $localFilePath
    ): ResponseInterface
    {
        $downloadUrl = $this->getFileRevisionDownloadUrl($library, $dirItem, $fileHistoryItem);

//        return $this->client->request('GET', $downloadUrl, ['save_to' => $localFilePath]);
        return $this->client->request('GET', $downloadUrl, ['sink' => $localFilePath]);
    }

**Comment by rene-s** [comment]
Hello @StephanTie, thank you for your suggestion. Please create a pull request, thank you very much.
